/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Accounts;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author vardha
 */
public class Diets extends javax.swing.JFrame {

    /**
     * Creates new form Diets
     */
    public Diets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("UPDATE DIETS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 20, 330, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(270, 160, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("ROOM ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 160, 80, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 120, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("ROOM NO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 120, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Lunch Off", "Lunch On", "Dinner Off", "Dinner On", "Mess Off" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(270, 240, 150, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(270, 200, 150, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("DATE(YYYY-MM-DD)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 200, 160, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("DIET");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 240, 50, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 300, 100, 30);

        jButton2.setText("BACK");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 10, 70, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-white-tiled-background-perspective-vector-illustration-58009965.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 80, 540, 300);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 550, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Diets.this.setVisible(false);
        DashBoard db=new DashBoard();
        db.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try
        {
             String rno=jTextField1.getText();
             String rid =jTextField2.getText();
             String date =jTextField3.getText();
             String diet=(String)jComboBox1.getSelectedItem();
             String query=null;
            Class.forName("com.mysql.jdbc.Driver");
            String path="jdbc:mysql://localhost/hostelmess";
            String user="root";
            String pass="login@mysql";
            Connection con=DriverManager.getConnection(path,user,pass);
            Statement stmt=con.createStatement(); 
            if(diet.equals("Lunch Off"))
            {
            query = "update diets set LUNCH=0 where (ROOM_NO,ROOM_ID,date(DATE))=('"+rno+"','"+rid+"','"+date+"')";
            String str="Lunch OFF of "+rno+" "+rid+" for "+date;
                String q="insert into activity(activity_log) values('"+str+"')";
                stmt.executeUpdate(q);
               
            }
            else if(diet.equals("Lunch On"))
            {
               query = "update diets set LUNCH=1 where (ROOM_NO,ROOM_ID,date(DATE))=('"+rno+"','"+rid+"','"+date+"')";
               String str="Lunch ON of "+rno+" "+rid+" for "+date;
                String q="insert into activity(activity_log) values('"+str+"')";
                stmt.executeUpdate(q);
               
               
            }
            else if(diet.equals("Dinner Off"))
            {
                query = "update diets set DINNER=0 where (ROOM_NO,ROOM_ID,date(DATE))=('"+rno+"','"+rid+"','"+date+"')";
                String str="Dinner OFF of "+rno+" "+rid+" for "+date;
                String q="insert into activity(activity_log) values('"+str+"')";
                stmt.executeUpdate(q);
               
            }
            else if(diet.equals("Dinner On"))
            {
                query = "update diets set DINNER=1 where (ROOM_NO,ROOM_ID,date(DATE))=('"+rno+"','"+rid+"','"+date+"')";
                String str="Dinner ON of "+rno+" "+rid+" for "+date;
                String q="insert into activity(activity_log) values('"+str+"')";
                stmt.executeUpdate(q);
              
            }
            else if(diet.equals("Mess Off"))
            {
                query = "update diets set DINNER=0,LUNCH=0 where (ROOM_NO,ROOM_ID,date(DATE))=('"+rno+"','"+rid+"','"+date+"')";
                String str="Mess OFF of "+rno+" "+rid+" for "+date;
                String q="insert into activity(activity_log) values('"+str+"')";
                stmt.executeUpdate(q);
               
            }
            else
            {
                JOptionPane.showMessageDialog(null,"select appropriate option");
            }
                  
            stmt.executeUpdate(query);
            String a="ALTER TABLE activity ORDER BY Date DESC";
            stmt.executeUpdate(a);
            JOptionPane.showMessageDialog(null,"successfully added");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error Found"+e);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
