package Accounts;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vardha
 */
public class generate_bill extends javax.swing.JFrame {

    /**
     * Creates new form generate_bill
     */
    public generate_bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("SELECT DATE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 30, 300, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("FROM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 150, 70, 30);

        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });
        jPanel1.add(date2);
        date2.setBounds(330, 140, 130, 40);

        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        jPanel1.add(date1);
        date1.setBounds(120, 140, 120, 40);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("TO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 150, 60, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("CALCULATE BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 240, 190, 40);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("(YYYY-MM-DD)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 180, 120, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("(YYYY-MM-DD)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 180, 120, 30);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 100, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-white-tiled-background-perspective-vector-illustration-58009965.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 80, 510, 230);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String d1=date1.getText();
        String d2=date2.getText();
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String path="jdbc:mysql://localhost/hostelmess";
            String user="root";
            String pass="login@mysql";
            Connection con=DriverManager.getConnection(path,user,pass);
            String query3="Select * from students";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(query3);
           
            while(rs.next())
            {
               stmt=con.createStatement();
                int dinner=0,lunch=0,extras=0;
                String roomno=rs.getString("ROOM_NO");
                String roomid=rs.getString("ROOM_ID");
                String sql="SELECT DINNER FROM DIETS where(ROOM_NO,ROOM_ID)=('"+roomno+"','"+roomid+"') AND date(DATE) BETWEEN '"+d1+"'  AND '"+d2+"' ";
                String sql1="SELECT LUNCH FROM DIETS where(ROOM_NO,ROOM_ID)=('"+roomno+"','"+roomid+"') AND date(DATE) BETWEEN '"+d1+"'  AND '"+d2+"' ";
                String sql2="SELECT TOTAL FROM extras where(ROOM_NO,ROOM_ID)=('"+roomno+"','"+roomid+"') AND date(DATE) BETWEEN '"+d1+"'  AND '"+d2+"' ";
                 Statement stmt2=con.createStatement();
             Statement stmt3=con.createStatement();
              Statement stmt4=con.createStatement();
                ResultSet rs1=stmt2.executeQuery(sql);
                while(rs1.next())
                {
                    int sum=rs1.getInt(1);
                    dinner=dinner+sum;
                }
                
                ResultSet rs2=stmt3.executeQuery(sql1);
                while(rs2.next())
                {
                 int sum1=rs2.getInt(1); 
                 lunch=lunch+sum1;
                }
                
                ResultSet rs3=stmt4.executeQuery(sql2);
                while(rs3.next())
                {
                  int sum3=rs3.getInt(1);
                  extras=extras+sum3;
                  
                }
                
                String query5="INSERT INTO bill(ROOM_NO,ROOM_ID,Dinner_diets,Lunch_diets,Extras_cost) values('"+roomno+"','"+roomid+"','"+dinner+"','"+lunch+"','"+extras+"')"; 
                stmt.executeUpdate(query5);
                rs1.close();
                rs2.close();
                rs3.close();
                stmt2.close();
                stmt3.close();
                stmt4.close();
                
                
            }
            JOptionPane.showMessageDialog(this,"successfully generated");
        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this,"Error Found"+e);
         }
         finalbill fb=new finalbill();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashBoard db=new DashBoard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generate_bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
