/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Accounts;
import java.awt.Component;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
 
public class UpdateMenu extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMenu
     */
    public UpdateMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("hostelmess?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        menuQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Menu m");
        menuList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : menuQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        itemprice = new javax.swing.JTextField();
        itemname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        itemid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(itemprice);
        itemprice.setBounds(470, 260, 110, 30);
        jPanel1.add(itemname);
        itemname.setBounds(470, 210, 110, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel3.setText("UPDATE MENU");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 20, 320, 50);

        edit.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(100, 410, 80, 40);

        remove.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove);
        remove.setBounds(350, 340, 100, 40);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("PRICE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 260, 70, 30);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 340, 100, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("ITEM NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 210, 110, 30);

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 90, 70, 23);

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setFillsViewportHeight(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, menuList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productid}"));
        columnBinding.setColumnName("Productid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productname}"));
        columnBinding.setColumnName("Productname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productprice}"));
        columnBinding.setColumnName("Productprice");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 240, 260);
        jPanel1.add(itemid);
        itemid.setBounds(470, 160, 110, 30);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 170, 50, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-white-tiled-background-perspective-vector-illustration-58009965.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 80, 1335, 390);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 620, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        UpdateMenu.this.setVisible(false);
        DashBoard db=new DashBoard();
        db.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

   
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
            try {
                    String iname=itemname.getText();
                    String iprice=itemprice.getText();
                    String id=itemid.getText();
                     Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hostelmess", "root", "login@mysql");
                    Statement stmt=conn.createStatement();
                    String sql="delete from menu where Product_id='"+id+"'";
                      stmt.executeUpdate(sql);
                     /*String sql2="SET @num=0";
                     stmt.executeUpdate(sql2);
                     String sql3="UPDATE menu SET Product_id=@num=(@num+1)";
                     stmt.executeUpdate(sql3);*/
                     String str="Menu Item "+iname+" DELETED";
                     String q="insert into activity(activity_log) values('"+str+"')";
                     stmt.executeUpdate(q);
                     String a="ALTER TABLE activity ORDER BY Date DESC";
            stmt.executeUpdate(a);
                    JOptionPane.showMessageDialog(this, "successfully removed");
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }       
        
    }//GEN-LAST:event_removeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String iname=itemname.getText();
        System.out.print(iname);
        String iprice=itemprice.getText();
        System.out.print(iprice);
        String id=itemid.getText();
        System.out.print(id);
          try {
                     Class.forName("com.mysql.jdbc.Driver");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hostelmess", "root", "login@mysql");
                    Statement stmt=con.createStatement();
                    String query="update menu set Product_name='"+iname+"',Product_price='"+iprice+"' where Product_id='"+id+"'";
                    PreparedStatement ps = con.prepareStatement(query);
                    ps.executeUpdate();
                    
                    String str="Menu Item "+iname+" UPDATED";
                    String q="insert into activity(activity_log) values('"+str+"')";
                    stmt.executeUpdate(q);
                    String a="ALTER TABLE activity ORDER BY Date DESC";
                    stmt.executeUpdate(a);
                    JOptionPane.showMessageDialog(this, "successfully Updated");
                }
                
                catch (Exception w) {
                    JOptionPane.showMessageDialog(this, "Connection Error!");
                }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        
        int row = jTable1.getSelectedRow();
        int id=(int) jTable1.getModel().getValueAt(row,0);
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String path="jdbc:mysql://localhost/hostelmess";
            String user="root";
            String pass="login@mysql";
            Connection con=DriverManager.getConnection(path,user,pass);
            String query="Select PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE from menu where (PRODUCT_ID)=('"+id+"')";
            Statement stmt=con.createStatement();
            stmt.executeQuery(query);
          ResultSet rs = stmt.executeQuery(query);  
        while(rs.next()) { 
        itemid.setText(rs.getString("PRODUCT_ID"));
        itemname.setText(rs.getString("PRODUCT_NAME"));
        itemprice.setText(rs.getString("PRODUCT_PRICE"));
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error Found"+e);
        }
        
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField itemid;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextField itemprice;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.util.List<Accounts.Menu> menuList;
    private javax.persistence.Query menuQuery;
    private javax.swing.JButton remove;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
